# Generated by Django 5.1.6 on 2025-03-09 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefoni', models.CharField(max_length=15)),
                ('adresa', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Prona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=100)),
                ('lokacioni', models.CharField(max_length=100)),
                ('cmimi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statusi', models.CharField(choices=[('disponueshme', 'Disponueshme'), ('e rezervuar', 'E Rezervuar')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mirembajtje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pershkrimi', models.TextField()),
                ('data_kerkeses', models.DateField()),
                ('statusi', models.CharField(choices=[('ne pritje', 'Në Pritje'), ('ne progres', 'Në Progres'), ('perfunduar', 'Përfunduar')], max_length=20)),
                ('prona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.prona')),
            ],
        ),
        migrations.CreateModel(
            name='Rezervim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fillimi', models.DateField()),
                ('data_mbarimi', models.DateField()),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.klient')),
                ('prona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.prona')),
            ],
        ),
        migrations.CreateModel(
            name='Pagesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuma', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_pageses', models.DateField()),
                ('rezervim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.rezervim')),
            ],
        ),
    ]
