# Generated by Django 5.1.6 on 2025-03-09 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klient',
            options={'verbose_name_plural': 'Klientët'},
        ),
        migrations.AlterModelOptions(
            name='mirembajtje',
            options={'verbose_name_plural': 'Mirëmbajtjet'},
        ),
        migrations.AlterModelOptions(
            name='pagesa',
            options={'verbose_name_plural': 'Pagesat'},
        ),
        migrations.AlterModelOptions(
            name='prona',
            options={'verbose_name_plural': 'Pronat'},
        ),
        migrations.AlterModelOptions(
            name='rezervim',
            options={'verbose_name_plural': 'Rezervimet'},
        ),
        migrations.AlterField(
            model_name='klient',
            name='adresa',
            field=models.TextField(verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='emri',
            field=models.CharField(max_length=100, verbose_name='Emri'),
        ),
        migrations.AlterField(
            model_name='klient',
            name='telefoni',
            field=models.CharField(max_length=15, verbose_name='Telefoni'),
        ),
        migrations.AlterField(
            model_name='mirembajtje',
            name='data_kerkeses',
            field=models.DateField(auto_now_add=True, verbose_name='Data e Kërkesës'),
        ),
        migrations.AlterField(
            model_name='mirembajtje',
            name='pershkrimi',
            field=models.TextField(verbose_name='Përshkrimi'),
        ),
        migrations.AlterField(
            model_name='mirembajtje',
            name='prona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirembajtjet', to='properties.prona', verbose_name='Prona'),
        ),
        migrations.AlterField(
            model_name='mirembajtje',
            name='statusi',
            field=models.CharField(choices=[('ne pritje', 'Në Pritje'), ('ne progres', 'Në Progres'), ('perfunduar', 'Përfunduar')], default='ne pritje', max_length=20, verbose_name='Statusi'),
        ),
        migrations.AlterField(
            model_name='pagesa',
            name='data_pageses',
            field=models.DateField(auto_now_add=True, verbose_name='Data e Pagesës'),
        ),
        migrations.AlterField(
            model_name='pagesa',
            name='rezervim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagesat', to='properties.rezervim', verbose_name='Rezervimi'),
        ),
        migrations.AlterField(
            model_name='pagesa',
            name='shuma',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shuma'),
        ),
        migrations.AlterField(
            model_name='prona',
            name='cmimi',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Çmimi'),
        ),
        migrations.AlterField(
            model_name='prona',
            name='emri',
            field=models.CharField(max_length=100, verbose_name='Emri'),
        ),
        migrations.AlterField(
            model_name='prona',
            name='lokacioni',
            field=models.CharField(max_length=200, verbose_name='Lokacioni'),
        ),
        migrations.AlterField(
            model_name='prona',
            name='statusi',
            field=models.CharField(choices=[('disponueshme', 'Disponueshme'), ('e rezervuar', 'E Rezervuar')], default='disponueshme', max_length=20, verbose_name='Statusi'),
        ),
        migrations.AlterField(
            model_name='rezervim',
            name='data_fillimi',
            field=models.DateField(verbose_name='Data Fillimit'),
        ),
        migrations.AlterField(
            model_name='rezervim',
            name='data_mbarimi',
            field=models.DateField(verbose_name='Data Mbarimit'),
        ),
        migrations.AlterField(
            model_name='rezervim',
            name='klient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervimet', to='properties.klient', verbose_name='Klienti'),
        ),
        migrations.AlterField(
            model_name='rezervim',
            name='prona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervimet', to='properties.prona', verbose_name='Prona'),
        ),
    ]
